-- Keep obsolete listing-image cleanup durable across request and Storage failures.
-- The table is intentionally service-only: users interact through owner-checked routes.
create table public.listing_image_cleanup_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  listing_id uuid,
  image_url text not null,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, image_url)
);

create index listing_image_cleanup_jobs_user_created_idx
  on public.listing_image_cleanup_jobs (user_id, created_at, id);

alter table public.listing_image_cleanup_jobs enable row level security;
revoke all on table public.listing_image_cleanup_jobs from anon, authenticated;
revoke all on sequence public.listing_image_cleanup_jobs_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.listing_image_cleanup_jobs to service_role;
grant usage, select on sequence public.listing_image_cleanup_jobs_id_seq to service_role;

create or replace function private.queue_obsolete_listing_images()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed_urls text[];
begin
  if tg_op = 'DELETE' then
    removed_urls := coalesce(old.images, '{}'::text[]);
  else
    select coalesce(array_agg(previous_url), '{}'::text[])
      into removed_urls
    from unnest(coalesce(old.images, '{}'::text[])) as previous_url
    where not (previous_url = any(coalesce(new.images, '{}'::text[])));
  end if;

  insert into public.listing_image_cleanup_jobs (
    user_id,
    listing_id,
    image_url
  )
  select old.seller_id, old.id, image_url
  from unnest(removed_urls) as image_url
  where image_url is not null and image_url <> ''
  on conflict (user_id, image_url) do update
    set listing_id = excluded.listing_id,
        updated_at = now();

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.queue_obsolete_listing_images() from public;

create trigger queue_obsolete_listing_images
after update of images or delete on public.listings
for each row execute function private.queue_obsolete_listing_images();
